FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy dependency definitions
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy rest of the source code
COPY . .

# Run Jest tests in CI mode
CMD ["npx", "jest", "--ci"]