import React from 'react';
import { Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Paper } from '@mui/material';
import type { DashboardTopViolations } from '../../types';

/**
 * Props interface for TopTables component.
 * @property topTables - An array of objects representing the top tables with their names and violation counts.
 */
interface Props {
  topTables: DashboardTopViolations['top_tables'];
}

/**
 * TopTables component displays a table listing the top tables with the highest violation counts.
 * It presents the table name and corresponding count in a structured tabular format using Material-UI components.
 */
const TopTables: React.FC<Props> = ({ topTables }) => (
  <div>
    {/* Heading for the top tables section */}
    <h3 className="text-xl font-semibold mb-2">Top Tables</h3>

    {/* TableContainer provides a styled container with Paper component for elevation and background */}
    <TableContainer component={Paper}>
      {/* Table component to render tabular data with a smaller size */}
      <Table size="small">
        {/* TableHead contains the header row with column titles */}
        <TableHead>
          <TableRow>
            <TableCell>Table Name</TableCell>
            <TableCell align="right">Count</TableCell>
          </TableRow>
        </TableHead>

        {/* TableBody contains the rows of data generated by mapping over topTables */}
        <TableBody>
          {/* Map over the topTables array to render each table's data as a row */}
          {topTables.map(t => (
            <TableRow key={t.table_name}>
              {/* Table name displayed as the row header */}
              <TableCell component="th" scope="row">
                {t.table_name}
              </TableCell>
              {/* Count displayed aligned to the right */}
              <TableCell align="right">{t.count}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </TableContainer>
  </div>
);

export default TopTables;