apiVersion: apps/v1
kind: Deployment
metadata:
  name: rule-runner
  namespace: default
  labels:
    app: rule-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rule-runner
  template:
    metadata:
      labels:
        app: rule-runner
    spec:
      containers:
      - name: rule-runner
        image: rule-runner:latest
        imagePullPolicy: Never  # <<< Wichtig
        ports:
        - containerPort: 80
        env:
        - name: MAIN_DB_URL
          value: postgresql://user:password@postgres.default.svc.cluster.local:5432/Valiax